### ISSUE TITLE
DBT build errors

### ISSUE THREAD

**Issue by mycaule** [matsonj/nba-monte-carlo#147]
After running  `make build` and `make run`

```
20:27:38  Completed with 2 errors and 0 warnings:
20:27:38
20:27:38    Runtime Error in model reg_season_actuals_enriched (models/nba/analysis/reg_season_actuals_enriched.sql)
  IO Error: Cannot open file "/workspaces/nba-monte-carlo/data/data_catalog/analysis"/reg_season_actuals_enriched.parquet": No such file or directory
20:27:38
20:27:38    Runtime Error in model reg_season_summary (models/nba/analysis/reg_season_summary.sql)
  IO Error: Cannot open file "/workspaces/nba-monte-carlo/data/data_catalog/analysis"/reg_season_summary.parquet": No such file or directory
20:27:38
```

**Comment by matsonj** [comment]
Hi @mycaule - what env are you running on? Looks like the sources are adding a quote in the wrong place, which might be an issue with dbt-duckdb generating paths.

**Comment by mycaule** [comment]
In GitHub codespaces. I will check and run from a new one if I can reproduce.

**Comment by matsonj** [comment]
Thanks. Let me know if you see that again, because I use the codespaces all the time without issue but very possible there as case where it doesn't build.

**Comment by mycaule** [comment]
I was just missing a quote. 
To understand how the project worked, while doing `dbt run` in the `transform/` folder without Meltano, I wanted to replace some of the environment variables.

Can I ask you where the `DBT_DUCKDB_PATH` is set and what the `staging` and `prod` dbt targets are for ?

```
# transformations/profiles.yml

    dev:
      type: duckdb
      threads: 4
      external_root: "/workspaces/nba-monte-carlo/data/data_catalog/analysis"
      path: "{{ env_var('DBT_DUCKDB_PATH') }}"
    staging:
      type: duckdb
      threads: 4
      external_root: /tmp/data_catalog/conformed
    prod:
      type: duckdb
      threads: 4
      external_root: /tmp/data_catalog/conformed
```

Another thing I was wondering is if the `malloy/` folder was still interesting for exploration, since you can already explore the data with dbt power user extension and evidence ?

**Comment by matsonj** [comment]
HI @mycaule a few comments.

> To understand how the project worked, while doing dbt run in the transform/ folder without Meltano, I wanted to replace some of the environment variables.

yes this makes sense, meltano is in the project bc it is trivial to add new sources (at one point, the data ingestion was automated with 'spreadsheets-anywhere' but the source data has since been deprecated). It also does a good job of managing the dependencies between projects. if you do remove meltano, make sure to pin your dependencies in `requirements.txt` or similar so that you don't cross your version, especially with regard to duckdb.

> Can I ask you where the DBT_DUCKDB_PATH is set and what the staging and prod dbt targets are for ?

They aren't, because I stubbed out that functionality but never completed it.

> Another thing I was wondering is if the malloy/ folder was still interesting for exploration, since you can already explore the data with dbt power user extension and evidence ?

Yes, because there is no way to do EDA with the project. Since its my model, and I know it very well, I can use evidence in dev mode (ran via ```make dev``` ) and write the queries I need with some interactivity from the pages I am working on. But especially when taking more open ended approach, I've found the malloy bits to be interesting. I don't know where this goes long term, since I would love to surface some notion of "user modeling space" inside of evidence but they have no way to do that today and malloy isn't integrated to it. My goal would be since we have uSQL and certain datasets defined in parquet already, simply adding a web based way for users to use malloy inside the web deployment.
